name: Initialize

# Events that trigger this workflow
on:
  workflow_dispatch:
    inputs:
      group:
        description: "Maven Group Name"
        required: true

jobs:
  initialize:
    name: Initialize the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4

      - name: Setup environment
        run: |
          echo "repo_name=$(echo "$GITHUB_REPOSITORY" | cut -d "/" -f 2 -)" >> $GITHUB_ENV
          echo "lock_file=${GITHUB_WORKSPACE}/.github/initialized" >> $GITHUB_ENV
      
      - name: Check initialization state
        run: |
          (if [ -f "$HOME/lockfile" ]; then echo "Repository already initialized."; exit 1; else exit 0; fi)
        env:
          LOCK_FILE: ${{ env.lock_file }}

      - name: Update settings.gradle
        run: |
          sed -i "s/${PLACEHOLDER}/${REPLACE_WITH}/g" "$FILE"
        env:
          PLACEHOLDER: "##REPO_NAME##"
          REPLACE_WITH: ${{ env.repo_name }}
          FILE: "${{ github.workspace }}/application/settings.gradle"

      - name: Update Dockerfile
        run: |
          sed -i "s/${PLACEHOLDER}/${REPLACE_WITH}/g" "$FILE"
        env:
          PLACEHOLDER: "##REPO_NAME##"
          REPLACE_WITH: ${{ env.repo_name }}
          FILE: "${{ github.workspace }}/application/Dockerfile"

      - name: Update build.gradle
        run: |
          sed -i "s/${PLACEHOLDER}/${REPLACE_WITH}/g" "$FILE"
        env:
          PLACEHOLDER: "##GROUP_ID##"
          REPLACE_WITH: ${{ github.event.inputs.group }}
          FILE: "${{ github.workspace }}/application/build.gradle"

      - name: Initialization finished. Locking action...
        run: touch "$LOCK_FILE"
        env:
          LOCK_FILE: ${{ env.lock_file }}

      - name: Pushing changes to remote
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "feat: Initialized project"
          git push
