name: Test Core Module

# Events that trigger this workflow
on: [push, pull_request]

jobs:
  test-core-module:
    name: Test Core Module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./application
    steps:
      - name: Checkout 📥
        uses: actions/checkout@v2.3.4
      - name: Set up JDK 16 💿
        uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: '16'
          java-package: jdk
          cache: 'gradle'

      - name: Test App 🛃
        run: chmod +x gradlew && ./gradlew test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
